version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mental_health_db
    environment:
      POSTGRES_DB: mental_health_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - mental_health_network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: mental_health_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mental_health_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mental_health_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/mental_health_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-this
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - mental_health_network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  # AI Services (Python/FastAPI)
  ai-services:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
    container_name: mental_health_ai
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/service-account.json
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/mental_health_db
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - mental_health_network
    restart: unless-stopped
    volumes:
      - ./ai-services:/app
      - ./credentials:/app/credentials:ro

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mental_health_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_AI_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ai-services
    networks:
      - mental_health_network
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Nginx (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: mental_health_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
      - ai-services
    networks:
      - mental_health_network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  mental_health_network:
    driver: bridge
